cleaner output, label support

diff --git a/kubectl-viewsecret b/kubectl-viewsecret
--- a/kubectl-viewsecret
+++ b/kubectl-viewsecret
@@ -1,7 +1,9 @@
 #!/bin/sh
 ns_flag=''
 kube_config=''
+label=''
 secret=''
+multiple_possible=''
 
 # Loop through options to grab what we need
 while test $# -gt 0; do
@@ -16,12 +18,17 @@ while test $# -gt 0; do
       kube_config=$1
       shift
     ;;
+    -l|--label )
+      shift
+      label=$1
+      shift
+    ;;
     -* )
       echo "Option $1 not supported, run 'kubectl viewsecret help' for available options and examples."
       exit 1
     ;;
     help )
-      echo "kubectl viewsecret options:\n\t-n (or --namespace): specify the namespace context\n\t-k (or --kubeconfig): specify the kubeconfig context\nkubectl viewsecret example:\n\tkubectl viewsecret -k ~/mykubeconfig -n mynamespace mysecretname"
+      echo "kubectl viewsecret options:\n\t-n (or --namespace): specify the namespace context\n\t-k (or --kubeconfig): specify the kubeconfig context\n\t-l (or --label): specify a label to use for grabbing secrets' contents\nkubectl viewsecret examples:\n\tkubectl viewsecret -k ~/mykubeconfig -n mynamespace mysecretname\n\tkubectl viewsecret -k ~/mykubeconfig -n mynamespace -l app=helloworld"
       exit 0
     ;;
     * )
@@ -37,9 +44,18 @@ kubectl_command="kubectl get secret "
 # Exit if no secret name provided
 if [[ $secret != '' ]]; then
   kubectl_command+="${secret} "
+  if [[ $label != '' ]]; then
+    echo "ERROR: Both secret name and label provided. Only one of these options can be passed in a single command.\nRun 'kubectl viewsecret help' for available options and examples."
+    exit 1
+  fi
 else
-  echo "ERROR: No secret name provided, run 'kubectl viewsecret help' for available options and examples."
-  exit 1
+  if [[ $label != '' ]]; then
+    kubectl_command+="-l $label "
+    multiple_possible="true"
+  else
+    echo "ERROR: No secret name or label provided, run 'kubectl viewsecret help' for available options and examples."
+    exit 1
+  fi
 fi
 
 # Tack on ns flag as needed
@@ -59,7 +75,11 @@ if [[ ! $($kubectl_command 2> /dev/null) ]]; then
 fi
 
 # Add our fancy decode magic
-kubectl_command+="-o go-template='{{range \$k,\$v := .data}}{{printf \"%s: \n---\n\" \$k}}{{if not \$v}}{{\$v}}{{else}}{{\$v | base64decode}}{{end}}{{\"\n\n\"}}{{end}}'"
+if [[ $multiple_possible == "true" ]]; then
+  kubectl_command+="-o go-template='{{range \$secret,\$contents := .items}}{{printf \"------\nSecret \`%s\`: \n------\n\" \$contents.metadata.name}}{{range \$k,\$v := \$contents.data}}{{printf \"Key \`%s\`: \n---\n\" \$k}}{{if not \$v}}{{\$v}}{{else}}{{\$v | base64decode}}{{end}}{{\"\n\n\"}}{{end}}{{end}}'"
+else
+  kubectl_command+="-o go-template='{{printf \"------\nSecret \`%s\`: \n------\n\" .metadata.name}}{{range \$k,\$v := .data}}{{printf \"Key \`%s\`: \n---\n\" \$k}}{{if not \$v}}{{\$v}}{{else}}{{\$v | base64decode}}{{end}}{{\"\n\n\"}}{{end}}'"
+fi
 
 # Execute
 eval $kubectl_command
